version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dumbot:latest .
      - docker tag dumbot:latest 332005788966.dkr.ecr.us-east-2.amazonaws.com/dumbot:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 332005788966.dkr.ecr.us-east-2.amazonaws.com/dumbot:latest
